language: erlang
otp_release:
  - 17.0
  - R16B02
  - R16B01
  - R15B01
script: make travis
branches:
  only:
    - rebar3
before_deploy: "rm -rf !(rebar3)"
deploy:
  on:
    branch: rebar3
    condition: $TRAVIS_OTP_RELEASE = R15B01
  provider: s3
  access_key_id: AKIAJAPYAQEFYCYSNL7Q
  secret_access_key:
    secure: "BUv2KQABv0Q4e8DAVNBRTc/lXHWt27yCN46Fdgo1IrcSSIiP+hq2yXzQcXLbPwkEu6pxUZQtL3mvKbt6l7uw3wFrcRfFAi1PGTITAW8MTmxtwcZIBcHSk3XOzDbkK+fYYcaddszmt7hDzzEFPtmYXiNgnaMIVeynhQLgcCcIRRQ="
  bucket: "rebar3"
  skip_cleanup: true
